version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql:8.0.26
    container_name: mysql-db2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=sathish
    ports:
      - "3306:3306"
    restart: always

  #service 2: definition of your spring-boot app
  customerservice:                        #it is just a name, which will be used only in this file.
    image: customer-service               #name of the image after dockerfile executes
    container_name: customer-service-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker containter port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/foodOrder?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: sathish
      SPRING_DATASOURCE_PASSWORD: password
